version: '3.3'
services:
  db:
    image: postgres:14.6
    volumes:
      - /db_backup/:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5433:5432
  laravel:
    build: ./main-service
    container_name: edu-1
    restart: always
    ports:
      - 3000:8080
    depends_on:
      - db
  java:
    build: ./user-service
    depends_on:
      - laravel
    restart: on-failure
    environment:
      - DB_HOST=db:5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./gateway/conf.d:/etc/nginx/conf.d:ro
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel
      - java